### ISSUE TITLE
Logger implementation upgrade - allow a callback

### ISSUE THREAD

**Issue by autodidaddict** [wapc/wapc-rust#10]
Right now the `waPC` standard exposes a single function that allows an actor to emit log text. The current naive implementation in Rust is to simply dump that information to STDOUT. This prevents higher-level projects written using waPC (like [waSCC](https://github.com/wascc)) from being able to provide their own, more robust logging implementation.

**Comment by bketelsen** [comment]
I'll be working on this today

**Comment by autodidaddict** [comment]
This work was completed yesterday.
