### ISSUE TITLE
wapcurl?

### ISSUE THREAD

**Issue by srenatus** [wapc/wapc-rust#22]
Hi!

Similar to grpcurl for grpc, a small utility that offers a way to invoke a wapc call via the command line would be useful for debugging and development... I'm imagining something like

```
wapcurl [-e engine] [-d payload] <wasm file> <function>
```

I wouldn't be surprised if this existed already, so I figured I'd ask. 🙂

**Comment by autodidaddict** [comment]
There is a command called `wash` that's part of [wasmcloud](https://github.com/wasmcloud) that can do what grpcurl does and quite a bit more.

**Comment by srenatus** [comment]
Ah thanks, I've seen that but wasn't sure if it could work with plain wapc wasm modules. I'll have another look. 😃

**Comment by autodidaddict** [comment]
The only difference between a wapc module and a wasmcloud module is the embedded signature.

**Comment by srenatus** [comment]
Ah I see. I'll have to figure out how to embed one for my wasm modules then.

**Comment by autodidaddict** [comment]
You can use the wascap rust crate, which is what wasmcloud uses.

**Comment by srenatus** [comment]
FWIW https://github.com/jsoverson/wacl seems handy there, too. Almost the interface I had desired, except that it'll need signing, too.

**Comment by autodidaddict** [comment]
Yes wacl and wash are pretty similar.
